### ISSUE TITLE
关于论文中的一些不懂的地方

### ISSUE THREAD

**Issue by TccccD** [cuishuhao/GVB#2]
1. 在Figure 4中，分类层中减去了γi，是怎么反向得到image的变化的，用什么工具可以做到；
2. 在公式8，D*=D1+D2，在公式10，D*=D1-D2，论文中没有对D*=D1-D2有更多的解释，代码中也是D1-D2的实现。
    我理解是D2可以表示为“domain-invariant”？

**Comment by cuishuhao** [comment]
1. 在论文4.3部分的Representation visualization有详细的描述，就是自己构建一个简单的图片重构模块
2. 在判别器中,输出没有domain-invariant的概念，实际上D2没有严格的正负之分，可以认为是（-D2）辅助D1模块来实现更好的效果

**Comment by TccccD** [comment]
哦我看到了是 deconvolutional neural network ，感谢！

**Comment by TccccD** [comment]
@cuishuhao 我还有个问题，你有没有试过在GVB上加入BNM的效果

**Comment by cuishuhao** [comment]
由于是同时期并行的两个工作，所以我没尝试在GVB加BNM的效果。GVB本身loss不算少，如果再增加，感觉BNM的系数容易不好调节。

**Comment by TccccD** [comment]
@cuishuhao 
我发现用你开源的数据集txt可以达到0.95，但是如果我换个方式如：
label_list = os.listdir(data_dir)
images = []
for lb_id, lb in enumerate(label_list):
    lb_path = os.path.join(image_list, lb)
    images.extend([(os.path.join(lb_path, x), lb_id) for x in os.listdir(lb_path)])

精度就达不到0.95了，GVB貌似对数据顺序很敏感？

**Comment by cuishuhao** [comment]
数据集本身大小比较小，所以对读取顺序就会比较敏感，也许learning rate之类的变量调低一点，让模型收敛慢一点受到的影响会小一些
